version: '3'
services:
  Mongo_db:
    image: 'mongo'
    restart: always
    command: --serviceExecutor adaptive
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  library-app:
    build: .
    ports:
      - "8081:80"
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    - DefaultConnection__ConnectionString=mongodb://root:example@Mongo_db:27017/library/?authSource=admin
    - DefaultConnection__DataBaseName=library
    - JwtOptions__ValidAudience=https://localhost:8081
    - JwtOptions__Issuer=https://localhost:8081
    - JwtOptions__SecretKey=not_too_short_secret_otherwise_it_might_error
    - JwtOptions__ExpiryMinutes=1440